# ----------------------------------------------------------------------
# Environment variables

#  export COLORTERM="24bit"
#  export WORDCHARS="*?_-[]~=&;!#$%^(){}<>"
export MY_ZSH_DIR="$HOME/dotfiles/zsh"


# ----------------------------------------------------------------------
# Zstyles

autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'


# ----------------------------------------------------------------------
# PATH

PATH=$HOME/.local/bin:$PATH
PATH=/usr/local/bin:$PATH
export PATH
