# ----------------------------------------------------------------------
# Environment variables

export COLORTERM="24bit"
export MY_ZSH_DIR="$HOME/dotfiles/zsh"
export WORDCHARS="*?_-[]~=&;!#$%^(){}<>"


# ----------------------------------------------------------------------
# Zstyles

autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'


# ----------------------------------------------------------------------
# PATH

PATH=$HOME/.local/bin:$PATH
export PATH
